### ISSUE TITLE
fix typos in .py files and in .html files

### ISSUE THREAD

**Issue by lyfofvipin** [vipin3699/File-Server#24]

**Comment by bovem** [comment]
Hi, is this issue still open?

**Comment by lyfofvipin** [comment]
Yep

**Comment by bovem** [comment]
I would like to work on it. Can you please assign it to me?

**Comment by lyfofvipin** [comment]
Sure :+1:

**Comment by bovem** [comment]
Merge Request opened at #48 .

**Comment by lyfofvipin** [comment]
Thanks @bovem  for the changes,

Closing the issue as most of the typos are fixed.
